import type ChatCompletionMessageParam from "../types/ChatCompletionMessageParam.js";

/**
 * Represents the request body for generating a Website using an LLM.
 *
 * @interface QueryRequestBody
 * @property {string} query - The text prompt to send to the LLM.
 * @property {boolean} [useLocalLLM=false] - If true, the query will be processed using a local LLM instead of a Groq.
 * @property {boolean} [skipContext=false] - If true, the LLM will skip ChromaDB context when generating the response.
 * @property {boolean} [stream=false] - If true, the response may be streamed in chunks rather than returned all at once.
 */
export interface QueryRequestBody {
    query: string;
    useLocalLLM?: boolean;
    skipContext?: boolean;
    stream?: boolean;
}

/**
 * Represents the response from an LLM generation query.
 *
 * @interface QueryResponseBody
 * @property {string} think - The LLM's internal reasoning or thought process for the query.
 * @property {string} response - The final response generated by the LLM (a JSON object in GrapesJS structure).
 * @property {number} total_duration - Total time in nanoseconds taken to generate the response.
 */
export interface QueryResponseBody {
    think: string;
    response: string;
    total_duration: number;
}

/**
 *
 * @interface ElementEditRequestBody
 * @param {ChatCompletionMessageParam[]} messages - Message history from the user/assistant.
 * @param {string} elementId - The ID of the element to be edited.
 * @param {string} websiteData - The website data to include in the prompt.
 */
export interface ElementEditRequestBody {
    messages: ChatCompletionMessageParam[];
    elementId: string;
    websiteData: string;
}

export interface ElementEditResponseBody {
    think: string;
    component: string;
    styles: string;
    total_duration: number;
}