import type ChatCompletionMessageParam from "../types/ChatCompletionMessageParam.js";

/**
 * Represents the request body for generating a Website using an LLM.
 *
 * @interface QueryRequestBody
 * @property {string} query - The text prompt to send to the LLM.
 * @property {string} [provider] - The inference provider used for the query.
 * @property {boolean} [skipContext=false] - If true, the LLM will skip ChromaDB context when generating the response.
 * @property {boolean} [stream=false] - If true, the response may be streamed in chunks rather than returned all at once.
 */
export interface QueryRequestBody {
    query: string;
    provider?: 'groq' | 'local';
    skipContext?: boolean;
    stream?: boolean;
}

/**
 * Represents the response from an LLM generation query.
 *
 * @interface QueryResponseBody
 * @property {string} think - The LLM's internal reasoning or thought process for the query.
 * @property {string} response - The final response generated by the LLM (a JSON object in GrapesJS structure).
 * @property {number} total_duration - Total time in nanoseconds taken to generate the response.
 */
export interface QueryResponseBody {
    think: string;
    response: string;
    total_duration: number;
}

/**
 *
 * @interface ElementEditRequestBody
 * @param {ChatCompletionMessageParam[]} messages - Message history from the user/assistant.
 * @param {string} elementId - The ID of the element to be edited.
 * @param {string} websiteData - The website data to include in the prompt.
 * @param {string} provider - The inference provider used for the query.
 */
export interface ElementEditRequestBody {
    messages: ChatCompletionMessageParam[];
    elementId: string;
    websiteData: string;
    provider?: 'groq' | 'local';
}

/**
 *
 * @interface ElementEditRequestBody
 * @param {string} think - Reasoning of reasoning LLMs. (only qwen3 or gpt currently support this)
 * @param {Object} component - The element data that was edited.
 * @param {Object} styles - The website styles data that was edited.
 * @param {number} total_duration - The time elapsed during the LLM request.
 */
export interface ElementEditResponseBody {
    think: string;
    text: string;
    component: Object;
    styles: Object;
    total_duration: number;
}